# Netlify headers to allow embedding Trivia in iframe

[[headers]]
  for = "/*"
  [headers.values]
  # Allow Convose domains and local dev to embed the game and set baseline CSP
  Content-Security-Policy = "frame-ancestors https://convose.com https://*.convose.com http://localhost:3000 http://localhost:5173 http://127.0.0.1:*; default-src 'self' https:; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; connect-src 'self' https: wss:;"

  # Ensure this is not set to DENY/SAMEORIGIN (CSP controls framing)
  X-Frame-Options = ""
